### ISSUE TITLE
Calendar contribution graph

### ISSUE THREAD

**Issue by pmqueiroz** [dracula/github#11]
The lil squares in contribution graph in profile have an aggressive (literally, my eye hurts) light color

That was my workaround to solve this:

```cs
--color-calendar-graph-day-bg: #323543
```

I'm not satisfied enough with my workaround but at least is not hurting my eye anymore

| ![image](https://user-images.githubusercontent.com/54639269/173166491-469c5881-968d-4f05-ab61-3435b08d2ac6.png) |
| ---|
| ![image](https://user-images.githubusercontent.com/54639269/173166483-42c79973-5794-4e81-ab7b-8c969a7f5258.png) |

**Comment by asportnoy** [comment]
Fixed in 9bcb171
