### ISSUE TITLE
Get started page not styled

### ISSUE THREAD

**Issue by Draculah** [dracula/github#13]
The [Github 'get started' page](https://github.com/join/get-started) is one I actually never open up, and don't really care about. I just noticed this page was unstyled and thought you may had forgotten about it. Actually it's odd that the styles don't work there (on my computer), but I'm quickly guessing it has different color definitions, or maybe Stylus doesn't work on the specific link for some reason. If you can't reproduce, I can of course investigate it.

Thanks for all the hard work; I'm amazed with the theme's granularity!

**Comment by asportnoy** [comment]
Hi, I am now taking over this project. Is this still an issue?

**Comment by Draculah** [comment]
It seems to be a different page than what I remembered, but the background is alright. I see now that I should have included a screenshot of my quick note after all, as we aren't able to check easily where it occurs. I'll close this issue. Good luck with styling github!
