### ISSUE TITLE
The style does not fit the github documentation

### ISSUE THREAD

**Issue by lvzhenbo** [dracula/github#14]
![屏幕截图 2022-09-25 152725](https://user-images.githubusercontent.com/32427677/192132990-3a8a2142-e7b4-4082-879a-6442af004e18.png)

**Comment by asportnoy** [comment]
Hi, I am now taking over this project. Is this still an issue?

**Comment by lvzhenbo** [comment]
I updated the version and now there is no problem, thanks a lot 👌
