### ISSUE TITLE
Hope to support a new code view

### ISSUE THREAD

**Issue by lvzhenbo** [dracula/github#21]
![image](https://github.com/dracula/github/assets/32427677/38794b24-b133-4732-90be-9900b67d6ff3)
[github blog](https://github.blog/2023-05-08-github-code-search-is-generally-available/)

**Comment by asportnoy** [comment]
@lvzhenbo cannot reproduce, is this still an issue?

**Comment by lvzhenbo** [comment]
> @lvzhenbo cannot reproduce, is this still an issue?

![image](https://github.com/dracula/github/assets/32427677/9eb443a3-9b66-4f07-a6c2-0de07009fa8e)

**Comment by lvzhenbo** [comment]
![image](https://github.com/dracula/github/assets/32427677/7a25e848-c535-4481-8caf-15cb5f16490d)
The same is true for the readme preview

**Comment by lvzhenbo** [comment]
I think it's because I opened github in daylight mode

**Comment by asportnoy** [comment]
Ah yeah, you'll need to use GitHub in dark mode for Dracula to work properly. Try that and let me know if it works.
