### ISSUE TITLE
Button contains black text instead of white

### ISSUE THREAD

**Issue by Elsie19** [dracula/github#6]
![image](https://user-images.githubusercontent.com/58742515/149425067-5dde7565-2211-4afc-b87c-9b5edb4e1904.png)
![image](https://user-images.githubusercontent.com/58742515/149604512-7a15442d-474e-4ba5-8d32-ec419dc21499.png)

**Comment by GlowingUmbreon** [comment]
This was actually at the request of zenorocha, see #4.
I will probably update it and make it a option instead.

**Comment by GlowingUmbreon** [comment]
This should be fixed in the update just released.
