### ISSUE TITLE
User icon cut off in discussions

### ISSUE THREAD

**Issue by Elsie19** [dracula/github#7]
![image](https://user-images.githubusercontent.com/58742515/150028772-6fda68fa-2e6e-4d15-899b-62a0bfacbedc.png)

**Comment by GlowingUmbreon** [comment]
I can't seem to reproduce this.
What is the resolution of your screen?

**Comment by Elsie19** [comment]
1920x1080

**Comment by GlowingUmbreon** [comment]
That is the same as my screen, I'm not sure what the problem could be.

**Comment by Elsie19** [comment]
Maybe the font?

**Comment by GlowingUmbreon** [comment]
> Maybe the font?

I've checked and I don't believe it is the font.

**Comment by asportnoy** [comment]
Hi, I am now taking over this project. Is this still an issue?

**Comment by Elsie19** [comment]
Not that I've noticed.
