### ISSUE TITLE
styles don't work

### ISSUE THREAD

**Issue by DaSh-More** [dracula/github#8]
All styles except the custom font don't work

Other styles for other sites work fine, if I try to write my own styles, they also work fine. I tried another computer, Vivaldi and Eage browsers.

Verdion 1.1.0

![image](https://user-images.githubusercontent.com/52647986/151600289-717cea84-7ae4-4a3c-a0b0-7d4851e63ddb.png)
![image](https://user-images.githubusercontent.com/52647986/151600855-9aa94daa-3fb0-47d0-8711-5e7c68f68c19.png)

**Comment by GlowingUmbreon** [comment]
Can you try a firefox browser and see if that works? This is a weird issue and I am unsure as to what oculd be causing it.

**Comment by GlowingUmbreon** [comment]
Can you try the update I just released? This should fix it when the color scheme is set to automatic.

**Comment by DaSh-More** [comment]
Thanks, everything worked!
