### ISSUE TITLE
Notifications screen

### ISSUE THREAD

**Issue by makenova** [dracula/github#9]
The notifications in the list have some sort of white background.

I added `--color-notifications-row-bg: #44475a;` to the Stylus stylesheet as a temporary work around and it seems to work for me.

Current issue on [notifications page](https://github.com/notifications):
![image](https://user-images.githubusercontent.com/941708/159053232-29ab3a1b-3e74-4c7a-928b-3de43be749e8.png)

With work around: 
![image](https://user-images.githubusercontent.com/941708/159054551-734605a2-ad14-4797-97aa-dbe1725a00a1.png)

Edit: I've switched to `#282a36` instead of `#44475a` and I prefer that. =)

**Comment by GlowingUmbreon** [comment]
![image](https://user-images.githubusercontent.com/37640997/173181107-52f21484-8155-4e6e-9703-4e88aedce79c.png)
hm some reason it isn't doing that for me, I might need to figure out what causes it.

**Comment by makenova** [comment]
Might be an extension on my end. 
I’ll report back in a bit.

**Comment by makenova** [comment]
I do not believe it's an extension on my part. That style, `--color-notifications-row-bg` is not in the [`style.user.css`](https://github.com/dracula/github/blob/master/style.user.css) file.

May be you have dark mode enabled in your [github settings](https://github.com/settings/appearance)?

**Comment by asportnoy** [comment]
Hi, I am now taking over this project. Is this still an issue?

**Comment by pmqueiroz** [comment]
It seems to be fixed to me @asportnoy
